### ISSUE TITLE
git clone git://gcc.gnu.org/git/gcc.git SomeLocalDir

### ISSUE THREAD

**Issue by ADM750** [ATS527/ATS527#3]

**Comment by ATS527** [comment]
Are you kidding me vro?

**Comment by ADM750** [comment]
Yep

**Comment by ATS527** [comment]
Do something usefull vro ;_; this is not realtime chat app

**Comment by ADM750** [comment]
First I need a gcc to do something please provide me some download link

**Comment by ATS527** [comment]
will do with team viewer tomorrow
